#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -N geoScrape
#PBS -j oe

cd /users/a/r/areagan/scratch/geotweets

# /usr/bin/time -v tar -xzOf /users/c/d/cdanfort/scratch/twitter/spritzer/zipped-raw/${DATE}.tgz | grep -v "{\"delete\"" | grep -v "\"coordinates\":null" >> zipped-raw/${DATE}.geo.json
/usr/bin/time -v tar -xzOf /users/c/d/cdanfort/scratch/twitter/tweet-troll/zipped-raw/${DATE}.tgz | grep -v "{\"delete\"" | grep -v "\"coordinates\":null" >> zipped-raw/${DATE}.geo.json


